mydata <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings = c("?"))
mydata$Date <- as.Date(as.character(mydata$Date), format="%d/%m/%Y")
startdate <- as.Date("2007-02-01", format="%Y-%m-%d")
enddate <- as.Date("2007-02-02", format="%Y-%m-%d")
dataset <- subset(mydata, Date>=startdate & Date<=enddate)
hist(dataset$Global_active_power, xlab = "Global Active Power (kilowatts)", ylab = "Frequency", col = "red", main = "Global Active Power")
dev.copy(png, "plot1.png")
dev.off()
#dataset$Time <- strftime(dataset$Time, format = "%H:%M:%S", tz="")
#head(dataset)