mydata <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings = c("?"))
mydata$Date <- as.Date(as.character(mydata$Date), format="%d/%m/%Y")
startdate <- as.Date("2007-02-01", format="%Y-%m-%d")
enddate <- as.Date("2007-02-02", format="%Y-%m-%d")
dataset <- subset(mydata, Date>=startdate & Date<=enddate)
dataset$timetemp <- paste(dataset$Date, dataset$Time)
dataset$Time <- strptime(dataset$timetemp, format = "%Y-%m-%d %H:%M:%S")
with(dataset, plot(Time, as.numeric(Sub_metering_1), main = "", type = "l", ylab = "Energy sub metering", xlab = ""))
with(dataset, points(Time, as.numeric(Sub_metering_2), type="l", col="red"))
with(dataset, points(Time, as.numeric(Sub_metering_3), type="l", col="blue"))
legend("topright", lty=1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, "plot3.png")
dev.off()