mydata <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings = c("?"))
mydata$Date <- as.Date(as.character(mydata$Date), format="%d/%m/%Y")
startdate <- as.Date("2007-02-01", format="%Y-%m-%d")
enddate <- as.Date("2007-02-02", format="%Y-%m-%d")
dataset <- subset(mydata, Date>=startdate & Date<=enddate)
dataset$timetemp <- paste(dataset$Date, dataset$Time)
dataset$Time <- strptime(dataset$timetemp, format = "%Y-%m-%d %H:%M:%S")
with(dataset, plot(Time, as.numeric(Global_active_power), main = "Global Active Power", type = "l", ylab = "Global Active Power (kilowatts)", xlab = ""))
dev.copy(png, "plot2.png")
dev.off()